apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: httpbin
  namespace: foo
spec:
  rules:
    - services: ["httpbin.foo.svc.cluster.local"]
      paths: ["*"]
      methods: ["*"]